name: Build Neovim AppImage (arm64 Ubuntu20.04)

on:
  workflow_dispatch:
  schedule: # monthly
    - cron: '0 0 1 * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      NEOVIM_BRANCH: stable
      NEOVIM_IMAGE: nvim-linux-arm64.appimage
    steps:
      - name: Build in Ubuntu 20.04 container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:20.04
          options: |
            -v ${{ github.workspace }}:/github_workspace
            -e DEBIAN_FRONTEND=noninteractive
            -e NEOVIM_BRANCH=${{ env.NEOVIM_BRANCH }}
            -e NEOVIM_IMAGE=${{ env.NEOVIM_IMAGE }}
          run: |
            # Install dependencies
            apt-get update && apt-get install -y --no-install-recommends \
              git \
              curl \
              file \
              unzip \
              gettext \
              cmake \
              ninja-build \
              build-essential \
              ca-certificates

            # Build Neovim
            git clone -b ${NEOVIM_BRANCH} --single-branch --depth 1 https://github.com/neovim/neovim.git
            cd neovim
            make CMAKE_BUILD_TYPE=RelWithDebInfo \
                 CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$PWD/build/nvim.AppDir/usr"
            make install

            # Create appimage
            curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage
            chmod +x linuxdeploy-aarch64.AppImage
            export OUTPUT=${NEOVIM_IMAGE}
            ./linuxdeploy-aarch64.AppImage --appimage-extract-and-run \
              --appdir build/nvim.AppDir \
              -d runtime/nvim.desktop \
              -i runtime/nvim.png \
              --output appimage

            # Move the AppImage to the mounted workspace
            mv ${NEOVIM_IMAGE} /github_workspace/

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: ${{ env.NEOVIM_IMAGE }}
          retention-days: 1

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEOVIM_BRANCH }}
          name: Nvim ${{ env.NEOVIM_BRANCH }} AppImage (arm64 Ubuntu20.04)
          body: |
            This is an automatically built AppImage of Neovim (${{ env.NEOVIM_BRANCH }}, arm64, Ubuntu20.04).
            Download `${{ env.NEOVIM_IMAGE }}` and make it executable:

            ```bash
            chmod +x ${{ env.NEOVIM_IMAGE }}
            ./${{ env.NEOVIM_IMAGE }}
            ```

            ---
            **License**:
            Distributed under the [Apache 2.0 license](https://github.com/neovim/neovim/blob/master/LICENSE.txt).
            Neovim is developed by the [Neovim project](https://github.com/neovim/neovim.git).
          files: ${{ env.NEOVIM_IMAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
