name: Build Neovim AppImage (arm64 Ubuntu20.04)

on:
  workflow_dispatch:
  push:
    tags:
      - 'stable'
  schedule: # monthly
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      NEOVIM_BRANCH: stable
    steps:
      - name: Build in Ubuntu 20.04 container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:20.04
          options: -v ${{ github.workspace }}:/work -e DEBIAN_FRONTEND=noninteractive
          run: |
            apt-get update && apt-get install -y --no-install-recommends \
              git \
              curl \
              unzip \
              gettext \
              cmake \
              ninja-build \
              build-essential \
              ca-certificates

            git clone -b stable --single-branch --depth 1 https://github.com/neovim/neovim.git
            sed -i 's|cmake --install build --prefix=.*|cd build\nmake install DESTDIR="$APP_BUILD_DIR/${APP_DIR}"\ncd ..|' neovim/scripts/genappimage.sh
            cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: neovim/build/bin/nvim-linux-*.appimage
          retention-days: 1

