name: Build Neovim AppImage (arm64 Ubuntu20.04)

on:
  workflow_dispatch:
  push:
    tags:
      - 'stable'
  schedule: # monthly
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    env:
      NEOVIM_BRANCH: stable
    steps:
      - name: Build in Ubuntu 20.04 container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:20.04
          options: -v ${{ github.workspace }}:/work -e DEBIAN_FRONTEND=noninteractive
          run: |
            # Install dependencies
            apt-get update && apt-get install -y --no-install-recommends \
              git \
              curl \
              file \
              unzip \
              gettext \
              cmake \
              ninja-build \
              build-essential \
              ca-certificates

            # Build Neovim
            git clone -b stable --single-branch --depth 1 https://github.com/neovim/neovim.git
            cd neovim
            make CMAKE_BUILD_TYPE=RelWithDebInfo \
                 CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$PWD/build/nvim.AppDir/usr"
            make install

            # Create appimage
            curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-aarch64.AppImage
            chmod +x linuxdeploy-aarch64.AppImage
            ./linuxdeploy-aarch64.AppImage --appimage-extract-and-run \
              --appdir build/nvim.AppDir \
              -d runtime/nvim.desktop \
              -i runtime/nvim.png \
              --output appimage

            ls -lh

      - name: List AppImage details
        run: ls -lh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage
          path: neovim/nvim-linux-*.appimage
          retention-days: 1

